import * as fs from "fs/promises";
import * as path from "path";
import { ProjectState } from "./projectState.js";
import { readMarkdownFiles } from "./fileUtils.js";

const GITHUB_DIR = ".github";
const INSTRUCTIONS_FILE = "copilot-instructions.md";
const KNOWLEDGE_DIR = path.join(".cpsagentkit", "knowledge");
const BEST_PRACTICES_DIR = path.join(".cpsagentkit", "bestpractices");
const TEMPLATES_DIR = path.join(".cpsagentkit", "templates");

/**
 * Determine which workflow phase the project is in based on file existence.
 */
function detectPhase(state: ProjectState): string {
  if (state.hasSpec && state.hasArchitecture) {
    return "Build";
  }
  if (state.hasSpec) {
    return "Architect";
  }
  return "Define";
}

/** Build a project state awareness section for the instructions */
function buildProjectStateSection(state: ProjectState): string {
  const phase = detectPhase(state);
  const lines: string[] = [
    "## Current Project State",
    "",
    `- **Current phase:** ${phase}`,
    `- **spec.md:** ${state.hasSpec ? "exists (Requirements/spec.md)" : "not yet created"}`,
    `- **architecture.md:** ${state.hasArchitecture ? "exists (Requirements/architecture.md)" : "not yet created"}`,
    `- **Knowledge synced:** ${state.hasKnowledge ? "yes" : "no"}`,
    `- **Requirements docs:** ${state.hasRequirementsDocs ? "Requirements/docs/ exists" : "no additional docs"}`,
    `- **Best practices:** ${state.hasBestPractices ? "docs/bestpractices/ exists" : "no custom best practices"}`,
  ];

  if (state.hasCpsExtensionAgent) {
    lines.push(
      `- **CPS agents in workspace:** ${state.agentFolders.join(", ")}`,
    );
  } else {
    lines.push("- **CPS agents in workspace:** none detected");
  }

  // Phase-specific guidance
  lines.push("");
  switch (phase) {
    case "Define":
      lines.push(
        "**Next step:** Ask the developer what they need and create `spec.md`.",
      );
      break;
    case "Architect":
      lines.push(
        "**Next step:** Read `spec.md` and the knowledge files, then create `architecture.md`.",
      );
      break;
    case "Build":
      lines.push(
        "**Next step:** Generate or refine agent instructions, topics, tools. Track progress in `architecture.md` Build State section.",
      );
      break;
  }

  return lines.join("\n");
}

/**
 * Generate the .github/copilot-instructions.md file by combining:
 * 1. The copilot-instructions-template.md (static workflow + role)
 * 2. All knowledge files as inline sections
 * 3. Best practice files as inline sections
 * 4. Current project state awareness
 */
export async function generateInstructions(
  workspaceRoot: string,
  templateDir: string,
  state: ProjectState,
): Promise<void> {
  // Read the template
  const templatePath = path.join(
    templateDir,
    "copilot-instructions-template.md",
  );
  let template: string;
  try {
    template = await fs.readFile(templatePath, "utf-8");
  } catch {
    throw new Error(
      `Could not read copilot-instructions-template.md from ${templateDir}`,
    );
  }

  // List knowledge files (by name only — content is read on demand by Copilot)
  const knowledgeDir = path.join(workspaceRoot, KNOWLEDGE_DIR);
  const knowledgeFiles = await readMarkdownFiles(knowledgeDir);
  const knowledgeFileList = knowledgeFiles.map(
    ({ filename }) => `- \`.cpsagentkit/knowledge/${filename}\``,
  );

  // List best practices files
  const bpDir = path.join(workspaceRoot, BEST_PRACTICES_DIR);
  const bestPracticesFiles = await readMarkdownFiles(bpDir);
  const bestPracticesFileList = bestPracticesFiles.map(
    ({ filename }) => `- \`.cpsagentkit/bestpractices/${filename}\``,
  );

  // List reference architecture template directories
  const tplDir = path.join(workspaceRoot, TEMPLATES_DIR);
  let templateDirNames: string[] = [];
  try {
    const tplEntries = await fs.readdir(tplDir, { withFileTypes: true });
    templateDirNames = tplEntries
      .filter((e) => e.isDirectory())
      .map((e) => e.name)
      .sort();
  } catch {
    // Templates directory doesn't exist yet
  }
  const templateDirList = templateDirNames.map(
    (name) => `- \`.cpsagentkit/templates/${name}/\``,
  );

  // Build project state section
  const projectStateSection = buildProjectStateSection(state);

  // Assemble final document — knowledge files are listed, not inlined.
  // Copilot reads the full files on demand via the path references.
  const parts = [
    "<!-- AUTO-GENERATED by CPS Architect. Do not edit manually. Regenerated on every knowledge sync. -->",
    "",
    template,
  ];

  if (knowledgeFileList.length > 0) {
    parts.push(
      "",
      "---",
      "",
      "## Available Knowledge Files",
      "",
      "Read these files when you need detailed platform knowledge for design, build, or troubleshooting decisions:",
      "",
      ...knowledgeFileList,
    );
  }

  if (bestPracticesFileList.length > 0) {
    parts.push(
      "",
      "## Available Best Practice Files",
      "",
      "Read these files when designing, building, or reviewing agents:",
      "",
      ...bestPracticesFileList,
    );
  }

  if (templateDirList.length > 0) {
    parts.push(
      "",
      "## Available Reference Architecture Templates",
      "",
      "Read these directories for proven multi-agent designs and working examples when proposing architectures:",
      "",
      ...templateDirList,
    );
  }

  parts.push("", "---", "", projectStateSection);

  const assembled = parts.join("\n");

  // Write to .github/copilot-instructions.md
  const outputDir = path.join(workspaceRoot, GITHUB_DIR);
  await fs.mkdir(outputDir, { recursive: true });
  await fs.writeFile(
    path.join(outputDir, INSTRUCTIONS_FILE),
    assembled,
    "utf-8",
  );
}
